name = "GregTech New Frontier"
author = "BGxArrow"
version = "0.4.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e18df6bb74d502985955fef0b17b1ca1c8bffa58b03ff4bc0736e41fb0ac1f07"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
