name = "GregTech New Frontier"
author = "BGxArrow"
version = "0.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3f4c66c9c690a33b95fc6bc693fab6344cbbdc55dbff02d5c363ee7a1ed60715"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
