name = "GregTech New Frontier"
author = "BGxArrow"
version = "0.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8f60d04f746f283c23abca3cc880136c4320772e3d6e3f8fa955ea6ed0bd5404"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
